### ISSUE TITLE
gwonepgen

### ISSUE THREAD

**Issue by ajloveslily14** [nucular/stuff#4]
gwonepgen is doin some weird stuff, http://corser.herokuapp.com/ seems to be down

**Comment by nucular** [comment]
Seems like Reddit started forcing HTTPS for API access, which is a good thing but breaks my CORS wrapper.

**Comment by ajloveslily14** [comment]
[redacted]

**Comment by nucular** [comment]
Eh, I wanted to rewrite that old thing anyway, it's full of security flaws.

**Comment by ajloveslily14** [comment]
I see
